services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: electro-tools-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  #  auth-service:
  #    image: quay.io/keycloak/keycloak:26.5.0
  #    environment:
  #      KC_BOOTSTRAP_ADMIN_USERNAME: admin
  #      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  #      KC_HOSTNAME: localhost
  #    ports:
  #      - "8081:8080"
  #    command: ["start-dev"]

  be-service:
    depends_on:
      - db
    #      - auth-service
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/electro-tools-db

volumes:
    db_data:
