spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/electro-tools-db

server.error.include-message=always

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/electro-tools
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/electro-tools/protocol/openid-connect/certs
genai.api.key=fill-in-your-api-key-here
