/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.TLoadElementsAud.TLoadElementsAudPath;
import pl.dabrowski.electrotools.jooq.tables.TOvercurrentProtectionElementsAud.TOvercurrentProtectionElementsAudPath;
import pl.dabrowski.electrotools.jooq.tables.TProjectsAud.TProjectsAudPath;
import pl.dabrowski.electrotools.jooq.tables.TRcdElementsAud.TRcdElementsAudPath;
import pl.dabrowski.electrotools.jooq.tables.TTerminalElementsAud.TTerminalElementsAudPath;
import pl.dabrowski.electrotools.jooq.tables.records.RevinfoRecord;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Revinfo extends TableImpl<RevinfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.revinfo</code>
     */
    public static final Revinfo REVINFO = new Revinfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RevinfoRecord> getRecordType() {
        return RevinfoRecord.class;
    }

    /**
     * The column <code>public.revinfo.rev</code>.
     */
    public final TableField<RevinfoRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.revinfo.revtstmp</code>.
     */
    public final TableField<RevinfoRecord, Long> REVTSTMP = createField(DSL.name("revtstmp"), SQLDataType.BIGINT, this, "");

    private Revinfo(Name alias, Table<RevinfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Revinfo(Name alias, Table<RevinfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.revinfo</code> table reference
     */
    public Revinfo(String alias) {
        this(DSL.name(alias), REVINFO);
    }

    /**
     * Create an aliased <code>public.revinfo</code> table reference
     */
    public Revinfo(Name alias) {
        this(alias, REVINFO);
    }

    /**
     * Create a <code>public.revinfo</code> table reference
     */
    public Revinfo() {
        this(DSL.name("revinfo"), null);
    }

    public <O extends Record> Revinfo(Table<O> path, ForeignKey<O, RevinfoRecord> childPath, InverseForeignKey<O, RevinfoRecord> parentPath) {
        super(path, childPath, parentPath, REVINFO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RevinfoPath extends Revinfo implements Path<RevinfoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RevinfoPath(Table<O> path, ForeignKey<O, RevinfoRecord> childPath, InverseForeignKey<O, RevinfoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RevinfoPath(Name alias, Table<RevinfoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RevinfoPath as(String alias) {
            return new RevinfoPath(DSL.name(alias), this);
        }

        @Override
        public RevinfoPath as(Name alias) {
            return new RevinfoPath(alias, this);
        }

        @Override
        public RevinfoPath as(Table<?> alias) {
            return new RevinfoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RevinfoRecord> getPrimaryKey() {
        return Keys.REVINFO_PKEY;
    }

    private transient TLoadElementsAudPath _tLoadElementsAud;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_load_elements_aud</code> table
     */
    public TLoadElementsAudPath tLoadElementsAud() {
        if (_tLoadElementsAud == null)
            _tLoadElementsAud = new TLoadElementsAudPath(this, null, Keys.T_LOAD_ELEMENTS_AUD__FK6R8OHSI9BYDL4DU55OIW31GNT.getInverseKey());

        return _tLoadElementsAud;
    }

    private transient TProjectsAudPath _tProjectsAud;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_projects_aud</code> table
     */
    public TProjectsAudPath tProjectsAud() {
        if (_tProjectsAud == null)
            _tProjectsAud = new TProjectsAudPath(this, null, Keys.T_PROJECTS_AUD__FKCSISWK63MJ80MHBXGM7SYYIMW.getInverseKey());

        return _tProjectsAud;
    }

    private transient TOvercurrentProtectionElementsAudPath _tOvercurrentProtectionElementsAud;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_overcurrent_protection_elements_aud</code> table
     */
    public TOvercurrentProtectionElementsAudPath tOvercurrentProtectionElementsAud() {
        if (_tOvercurrentProtectionElementsAud == null)
            _tOvercurrentProtectionElementsAud = new TOvercurrentProtectionElementsAudPath(this, null, Keys.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD__FKEBCFRE95GAUFT1EBO1RQUHE5T.getInverseKey());

        return _tOvercurrentProtectionElementsAud;
    }

    private transient TRcdElementsAudPath _tRcdElementsAud;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_rcd_elements_aud</code> table
     */
    public TRcdElementsAudPath tRcdElementsAud() {
        if (_tRcdElementsAud == null)
            _tRcdElementsAud = new TRcdElementsAudPath(this, null, Keys.T_RCD_ELEMENTS_AUD__FKH6KI2JI6DG3BTUM8SHEMS7ES.getInverseKey());

        return _tRcdElementsAud;
    }

    private transient TTerminalElementsAudPath _tTerminalElementsAud;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_terminal_elements_aud</code> table
     */
    public TTerminalElementsAudPath tTerminalElementsAud() {
        if (_tTerminalElementsAud == null)
            _tTerminalElementsAud = new TTerminalElementsAudPath(this, null, Keys.T_TERMINAL_ELEMENTS_AUD__FKIB9TINNVJAKFN4WRC7N877FTJ.getInverseKey());

        return _tTerminalElementsAud;
    }

    @Override
    public Revinfo as(String alias) {
        return new Revinfo(DSL.name(alias), this);
    }

    @Override
    public Revinfo as(Name alias) {
        return new Revinfo(alias, this);
    }

    @Override
    public Revinfo as(Table<?> alias) {
        return new Revinfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Revinfo rename(String name) {
        return new Revinfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Revinfo rename(Name name) {
        return new Revinfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Revinfo rename(Table<?> name) {
        return new Revinfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revinfo where(Condition condition) {
        return new Revinfo(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revinfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revinfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revinfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revinfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revinfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revinfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Revinfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revinfo whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Revinfo whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
