/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.TProjects.TProjectsPath;
import pl.dabrowski.electrotools.jooq.tables.records.TBasicElementsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TBasicElements extends TableImpl<TBasicElementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_basic_elements</code>
     */
    public static final TBasicElements T_BASIC_ELEMENTS = new TBasicElements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TBasicElementsRecord> getRecordType() {
        return TBasicElementsRecord.class;
    }

    /**
     * The column <code>public.t_basic_elements.id</code>.
     */
    public final TableField<TBasicElementsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_basic_elements.created_by</code>.
     */
    public final TableField<TBasicElementsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_basic_elements.created_date</code>.
     */
    public final TableField<TBasicElementsRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_basic_elements.modified_by</code>.
     */
    public final TableField<TBasicElementsRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_basic_elements.modified_date</code>.
     */
    public final TableField<TBasicElementsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_basic_elements.version</code>.
     */
    public final TableField<TBasicElementsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_basic_elements.label</code>.
     */
    public final TableField<TBasicElementsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_basic_elements.parent_id</code>.
     */
    public final TableField<TBasicElementsRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.t_basic_elements.diameter</code>.
     */
    public final TableField<TBasicElementsRecord, String> DIAMETER = createField(DSL.name("diameter"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_basic_elements.length</code>.
     */
    public final TableField<TBasicElementsRecord, Double> LENGTH = createField(DSL.name("length"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_basic_elements.phase</code>.
     */
    public final TableField<TBasicElementsRecord, String> PHASE = createField(DSL.name("phase"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_basic_elements.placement</code>.
     */
    public final TableField<TBasicElementsRecord, String> PLACEMENT = createField(DSL.name("placement"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_basic_elements.wire_type</code>.
     */
    public final TableField<TBasicElementsRecord, String> WIRE_TYPE = createField(DSL.name("wire_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_basic_elements.x</code>.
     */
    public final TableField<TBasicElementsRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_basic_elements.y</code>.
     */
    public final TableField<TBasicElementsRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_basic_elements.project_id</code>.
     */
    public final TableField<TBasicElementsRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID, this, "");

    private TBasicElements(Name alias, Table<TBasicElementsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TBasicElements(Name alias, Table<TBasicElementsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_basic_elements</code> table reference
     */
    public TBasicElements(String alias) {
        this(DSL.name(alias), T_BASIC_ELEMENTS);
    }

    /**
     * Create an aliased <code>public.t_basic_elements</code> table reference
     */
    public TBasicElements(Name alias) {
        this(alias, T_BASIC_ELEMENTS);
    }

    /**
     * Create a <code>public.t_basic_elements</code> table reference
     */
    public TBasicElements() {
        this(DSL.name("t_basic_elements"), null);
    }

    public <O extends Record> TBasicElements(Table<O> path, ForeignKey<O, TBasicElementsRecord> childPath, InverseForeignKey<O, TBasicElementsRecord> parentPath) {
        super(path, childPath, parentPath, T_BASIC_ELEMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TBasicElementsPath extends TBasicElements implements Path<TBasicElementsRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> TBasicElementsPath(Table<O> path, ForeignKey<O, TBasicElementsRecord> childPath, InverseForeignKey<O, TBasicElementsRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private TBasicElementsPath(Name alias, Table<TBasicElementsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TBasicElementsPath as(String alias) {
            return new TBasicElementsPath(DSL.name(alias), this);
        }

        @Override
        public TBasicElementsPath as(Name alias) {
            return new TBasicElementsPath(alias, this);
        }

        @Override
        public TBasicElementsPath as(Table<?> alias) {
            return new TBasicElementsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TBasicElementsRecord> getPrimaryKey() {
        return Keys.T_BASIC_ELEMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<TBasicElementsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_BASIC_ELEMENTS__FK39DHW07WI5ST8PSYYUTES9193);
    }

    private transient TProjectsPath _tProjects;

    /**
     * Get the implicit join path to the <code>public.t_projects</code> table.
     */
    public TProjectsPath tProjects() {
        if (_tProjects == null)
            _tProjects = new TProjectsPath(this, Keys.T_BASIC_ELEMENTS__FK39DHW07WI5ST8PSYYUTES9193, null);

        return _tProjects;
    }

    @Override
    public TBasicElements as(String alias) {
        return new TBasicElements(DSL.name(alias), this);
    }

    @Override
    public TBasicElements as(Name alias) {
        return new TBasicElements(alias, this);
    }

    @Override
    public TBasicElements as(Table<?> alias) {
        return new TBasicElements(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBasicElements rename(String name) {
        return new TBasicElements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBasicElements rename(Name name) {
        return new TBasicElements(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBasicElements rename(Table<?> name) {
        return new TBasicElements(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBasicElements where(Condition condition) {
        return new TBasicElements(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBasicElements where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBasicElements where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBasicElements where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBasicElements where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBasicElements where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBasicElements where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBasicElements where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBasicElements whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBasicElements whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
