/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.Revinfo.RevinfoPath;
import pl.dabrowski.electrotools.jooq.tables.records.TLoadElementsAudRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TLoadElementsAud extends TableImpl<TLoadElementsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_load_elements_aud</code>
     */
    public static final TLoadElementsAud T_LOAD_ELEMENTS_AUD = new TLoadElementsAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TLoadElementsAudRecord> getRecordType() {
        return TLoadElementsAudRecord.class;
    }

    /**
     * The column <code>public.t_load_elements_aud.id</code>.
     */
    public final TableField<TLoadElementsAudRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_load_elements_aud.rev</code>.
     */
    public final TableField<TLoadElementsAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.t_load_elements_aud.revtype</code>.
     */
    public final TableField<TLoadElementsAudRecord, Short> REVTYPE = createField(DSL.name("revtype"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.t_load_elements_aud.config</code>.
     */
    public final TableField<TLoadElementsAudRecord, String> CONFIG = createField(DSL.name("config"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements_aud.draw_power</code>.
     */
    public final TableField<TLoadElementsAudRecord, Double> DRAW_POWER = createField(DSL.name("draw_power"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_load_elements_aud.high_start_current</code>.
     */
    public final TableField<TLoadElementsAudRecord, Boolean> HIGH_START_CURRENT = createField(DSL.name("high_start_current"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.t_load_elements_aud.power_factor</code>.
     */
    public final TableField<TLoadElementsAudRecord, Double> POWER_FACTOR = createField(DSL.name("power_factor"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_load_elements_aud.zeroed</code>.
     */
    public final TableField<TLoadElementsAudRecord, Boolean> ZEROED = createField(DSL.name("zeroed"), SQLDataType.BOOLEAN, this, "");

    private TLoadElementsAud(Name alias, Table<TLoadElementsAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TLoadElementsAud(Name alias, Table<TLoadElementsAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_load_elements_aud</code> table reference
     */
    public TLoadElementsAud(String alias) {
        this(DSL.name(alias), T_LOAD_ELEMENTS_AUD);
    }

    /**
     * Create an aliased <code>public.t_load_elements_aud</code> table reference
     */
    public TLoadElementsAud(Name alias) {
        this(alias, T_LOAD_ELEMENTS_AUD);
    }

    /**
     * Create a <code>public.t_load_elements_aud</code> table reference
     */
    public TLoadElementsAud() {
        this(DSL.name("t_load_elements_aud"), null);
    }

    public <O extends Record> TLoadElementsAud(Table<O> path, ForeignKey<O, TLoadElementsAudRecord> childPath, InverseForeignKey<O, TLoadElementsAudRecord> parentPath) {
        super(path, childPath, parentPath, T_LOAD_ELEMENTS_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TLoadElementsAudPath extends TLoadElementsAud implements Path<TLoadElementsAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TLoadElementsAudPath(Table<O> path, ForeignKey<O, TLoadElementsAudRecord> childPath, InverseForeignKey<O, TLoadElementsAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TLoadElementsAudPath(Name alias, Table<TLoadElementsAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TLoadElementsAudPath as(String alias) {
            return new TLoadElementsAudPath(DSL.name(alias), this);
        }

        @Override
        public TLoadElementsAudPath as(Name alias) {
            return new TLoadElementsAudPath(alias, this);
        }

        @Override
        public TLoadElementsAudPath as(Table<?> alias) {
            return new TLoadElementsAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TLoadElementsAudRecord> getPrimaryKey() {
        return Keys.T_LOAD_ELEMENTS_AUD_PKEY;
    }

    @Override
    public List<ForeignKey<TLoadElementsAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_LOAD_ELEMENTS_AUD__FK6R8OHSI9BYDL4DU55OIW31GNT);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>public.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.T_LOAD_ELEMENTS_AUD__FK6R8OHSI9BYDL4DU55OIW31GNT, null);

        return _revinfo;
    }

    @Override
    public TLoadElementsAud as(String alias) {
        return new TLoadElementsAud(DSL.name(alias), this);
    }

    @Override
    public TLoadElementsAud as(Name alias) {
        return new TLoadElementsAud(alias, this);
    }

    @Override
    public TLoadElementsAud as(Table<?> alias) {
        return new TLoadElementsAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TLoadElementsAud rename(String name) {
        return new TLoadElementsAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TLoadElementsAud rename(Name name) {
        return new TLoadElementsAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TLoadElementsAud rename(Table<?> name) {
        return new TLoadElementsAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElementsAud where(Condition condition) {
        return new TLoadElementsAud(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElementsAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElementsAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElementsAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElementsAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElementsAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElementsAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElementsAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElementsAud whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElementsAud whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
