/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.TProjects.TProjectsPath;
import pl.dabrowski.electrotools.jooq.tables.records.TLoadElementsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TLoadElements extends TableImpl<TLoadElementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_load_elements</code>
     */
    public static final TLoadElements T_LOAD_ELEMENTS = new TLoadElements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TLoadElementsRecord> getRecordType() {
        return TLoadElementsRecord.class;
    }

    /**
     * The column <code>public.t_load_elements.id</code>.
     */
    public final TableField<TLoadElementsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_load_elements.created_by</code>.
     */
    public final TableField<TLoadElementsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.created_date</code>.
     */
    public final TableField<TLoadElementsRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_load_elements.modified_by</code>.
     */
    public final TableField<TLoadElementsRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.modified_date</code>.
     */
    public final TableField<TLoadElementsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_load_elements.version</code>.
     */
    public final TableField<TLoadElementsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_load_elements.label</code>.
     */
    public final TableField<TLoadElementsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.parent_id</code>.
     */
    public final TableField<TLoadElementsRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.t_load_elements.diameter</code>.
     */
    public final TableField<TLoadElementsRecord, String> DIAMETER = createField(DSL.name("diameter"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.length</code>.
     */
    public final TableField<TLoadElementsRecord, Double> LENGTH = createField(DSL.name("length"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_load_elements.phase</code>.
     */
    public final TableField<TLoadElementsRecord, String> PHASE = createField(DSL.name("phase"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.placement</code>.
     */
    public final TableField<TLoadElementsRecord, String> PLACEMENT = createField(DSL.name("placement"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.wire_type</code>.
     */
    public final TableField<TLoadElementsRecord, String> WIRE_TYPE = createField(DSL.name("wire_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.x</code>.
     */
    public final TableField<TLoadElementsRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_load_elements.y</code>.
     */
    public final TableField<TLoadElementsRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_load_elements.config</code>.
     */
    public final TableField<TLoadElementsRecord, String> CONFIG = createField(DSL.name("config"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_load_elements.draw_power</code>.
     */
    public final TableField<TLoadElementsRecord, Double> DRAW_POWER = createField(DSL.name("draw_power"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_load_elements.high_start_current</code>.
     */
    public final TableField<TLoadElementsRecord, Boolean> HIGH_START_CURRENT = createField(DSL.name("high_start_current"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.t_load_elements.power_factor</code>.
     */
    public final TableField<TLoadElementsRecord, Double> POWER_FACTOR = createField(DSL.name("power_factor"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_load_elements.zeroed</code>.
     */
    public final TableField<TLoadElementsRecord, Boolean> ZEROED = createField(DSL.name("zeroed"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.t_load_elements.project_id</code>.
     */
    public final TableField<TLoadElementsRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID, this, "");

    private TLoadElements(Name alias, Table<TLoadElementsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TLoadElements(Name alias, Table<TLoadElementsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_load_elements</code> table reference
     */
    public TLoadElements(String alias) {
        this(DSL.name(alias), T_LOAD_ELEMENTS);
    }

    /**
     * Create an aliased <code>public.t_load_elements</code> table reference
     */
    public TLoadElements(Name alias) {
        this(alias, T_LOAD_ELEMENTS);
    }

    /**
     * Create a <code>public.t_load_elements</code> table reference
     */
    public TLoadElements() {
        this(DSL.name("t_load_elements"), null);
    }

    public <O extends Record> TLoadElements(Table<O> path, ForeignKey<O, TLoadElementsRecord> childPath, InverseForeignKey<O, TLoadElementsRecord> parentPath) {
        super(path, childPath, parentPath, T_LOAD_ELEMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TLoadElementsPath extends TLoadElements implements Path<TLoadElementsRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> TLoadElementsPath(Table<O> path, ForeignKey<O, TLoadElementsRecord> childPath, InverseForeignKey<O, TLoadElementsRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private TLoadElementsPath(Name alias, Table<TLoadElementsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TLoadElementsPath as(String alias) {
            return new TLoadElementsPath(DSL.name(alias), this);
        }

        @Override
        public TLoadElementsPath as(Name alias) {
            return new TLoadElementsPath(alias, this);
        }

        @Override
        public TLoadElementsPath as(Table<?> alias) {
            return new TLoadElementsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TLoadElementsRecord> getPrimaryKey() {
        return Keys.T_LOAD_ELEMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<TLoadElementsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_LOAD_ELEMENTS__FKAOPRM7AO3HVQ1QIIAD64VX71O);
    }

    private transient TProjectsPath _tProjects;

    /**
     * Get the implicit join path to the <code>public.t_projects</code> table.
     */
    public TProjectsPath tProjects() {
        if (_tProjects == null)
            _tProjects = new TProjectsPath(this, Keys.T_LOAD_ELEMENTS__FKAOPRM7AO3HVQ1QIIAD64VX71O, null);

        return _tProjects;
    }

    @Override
    public TLoadElements as(String alias) {
        return new TLoadElements(DSL.name(alias), this);
    }

    @Override
    public TLoadElements as(Name alias) {
        return new TLoadElements(alias, this);
    }

    @Override
    public TLoadElements as(Table<?> alias) {
        return new TLoadElements(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TLoadElements rename(String name) {
        return new TLoadElements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TLoadElements rename(Name name) {
        return new TLoadElements(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TLoadElements rename(Table<?> name) {
        return new TLoadElements(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElements where(Condition condition) {
        return new TLoadElements(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElements where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElements where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElements where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElements where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElements where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElements where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TLoadElements where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElements whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TLoadElements whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
