/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.Revinfo.RevinfoPath;
import pl.dabrowski.electrotools.jooq.tables.records.TOvercurrentProtectionElementsAudRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TOvercurrentProtectionElementsAud extends TableImpl<TOvercurrentProtectionElementsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.t_overcurrent_protection_elements_aud</code>
     */
    public static final TOvercurrentProtectionElementsAud T_OVERCURRENT_PROTECTION_ELEMENTS_AUD = new TOvercurrentProtectionElementsAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TOvercurrentProtectionElementsAudRecord> getRecordType() {
        return TOvercurrentProtectionElementsAudRecord.class;
    }

    /**
     * The column <code>public.t_overcurrent_protection_elements_aud.id</code>.
     */
    public final TableField<TOvercurrentProtectionElementsAudRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements_aud.rev</code>.
     */
    public final TableField<TOvercurrentProtectionElementsAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements_aud.revtype</code>.
     */
    public final TableField<TOvercurrentProtectionElementsAudRecord, Short> REVTYPE = createField(DSL.name("revtype"), SQLDataType.SMALLINT, this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements_aud.amperage</code>.
     */
    public final TableField<TOvercurrentProtectionElementsAudRecord, Integer> AMPERAGE = createField(DSL.name("amperage"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements_aud.type</code>.
     */
    public final TableField<TOvercurrentProtectionElementsAudRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255), this, "");

    private TOvercurrentProtectionElementsAud(Name alias, Table<TOvercurrentProtectionElementsAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TOvercurrentProtectionElementsAud(Name alias, Table<TOvercurrentProtectionElementsAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased
     * <code>public.t_overcurrent_protection_elements_aud</code> table reference
     */
    public TOvercurrentProtectionElementsAud(String alias) {
        this(DSL.name(alias), T_OVERCURRENT_PROTECTION_ELEMENTS_AUD);
    }

    /**
     * Create an aliased
     * <code>public.t_overcurrent_protection_elements_aud</code> table reference
     */
    public TOvercurrentProtectionElementsAud(Name alias) {
        this(alias, T_OVERCURRENT_PROTECTION_ELEMENTS_AUD);
    }

    /**
     * Create a <code>public.t_overcurrent_protection_elements_aud</code> table
     * reference
     */
    public TOvercurrentProtectionElementsAud() {
        this(DSL.name("t_overcurrent_protection_elements_aud"), null);
    }

    public <O extends Record> TOvercurrentProtectionElementsAud(Table<O> path, ForeignKey<O, TOvercurrentProtectionElementsAudRecord> childPath, InverseForeignKey<O, TOvercurrentProtectionElementsAudRecord> parentPath) {
        super(path, childPath, parentPath, T_OVERCURRENT_PROTECTION_ELEMENTS_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TOvercurrentProtectionElementsAudPath extends TOvercurrentProtectionElementsAud implements Path<TOvercurrentProtectionElementsAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TOvercurrentProtectionElementsAudPath(Table<O> path, ForeignKey<O, TOvercurrentProtectionElementsAudRecord> childPath, InverseForeignKey<O, TOvercurrentProtectionElementsAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TOvercurrentProtectionElementsAudPath(Name alias, Table<TOvercurrentProtectionElementsAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TOvercurrentProtectionElementsAudPath as(String alias) {
            return new TOvercurrentProtectionElementsAudPath(DSL.name(alias), this);
        }

        @Override
        public TOvercurrentProtectionElementsAudPath as(Name alias) {
            return new TOvercurrentProtectionElementsAudPath(alias, this);
        }

        @Override
        public TOvercurrentProtectionElementsAudPath as(Table<?> alias) {
            return new TOvercurrentProtectionElementsAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TOvercurrentProtectionElementsAudRecord> getPrimaryKey() {
        return Keys.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD_PKEY;
    }

    @Override
    public List<ForeignKey<TOvercurrentProtectionElementsAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD__FKEBCFRE95GAUFT1EBO1RQUHE5T);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>public.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD__FKEBCFRE95GAUFT1EBO1RQUHE5T, null);

        return _revinfo;
    }

    @Override
    public TOvercurrentProtectionElementsAud as(String alias) {
        return new TOvercurrentProtectionElementsAud(DSL.name(alias), this);
    }

    @Override
    public TOvercurrentProtectionElementsAud as(Name alias) {
        return new TOvercurrentProtectionElementsAud(alias, this);
    }

    @Override
    public TOvercurrentProtectionElementsAud as(Table<?> alias) {
        return new TOvercurrentProtectionElementsAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TOvercurrentProtectionElementsAud rename(String name) {
        return new TOvercurrentProtectionElementsAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TOvercurrentProtectionElementsAud rename(Name name) {
        return new TOvercurrentProtectionElementsAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TOvercurrentProtectionElementsAud rename(Table<?> name) {
        return new TOvercurrentProtectionElementsAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElementsAud where(Condition condition) {
        return new TOvercurrentProtectionElementsAud(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElementsAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElementsAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElementsAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElementsAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElementsAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElementsAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElementsAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElementsAud whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElementsAud whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
