/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.TProjects.TProjectsPath;
import pl.dabrowski.electrotools.jooq.tables.records.TOvercurrentProtectionElementsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TOvercurrentProtectionElements extends TableImpl<TOvercurrentProtectionElementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.t_overcurrent_protection_elements</code>
     */
    public static final TOvercurrentProtectionElements T_OVERCURRENT_PROTECTION_ELEMENTS = new TOvercurrentProtectionElements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TOvercurrentProtectionElementsRecord> getRecordType() {
        return TOvercurrentProtectionElementsRecord.class;
    }

    /**
     * The column <code>public.t_overcurrent_protection_elements.id</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.created_by</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.created_date</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.modified_by</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.modified_date</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements.version</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements.label</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.parent_id</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.diameter</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> DIAMETER = createField(DSL.name("diameter"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements.length</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, Double> LENGTH = createField(DSL.name("length"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements.phase</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> PHASE = createField(DSL.name("phase"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.placement</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> PLACEMENT = createField(DSL.name("placement"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.wire_type</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> WIRE_TYPE = createField(DSL.name("wire_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements.x</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements.y</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.amperage</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, Integer> AMPERAGE = createField(DSL.name("amperage"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_overcurrent_protection_elements.type</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column
     * <code>public.t_overcurrent_protection_elements.project_id</code>.
     */
    public final TableField<TOvercurrentProtectionElementsRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID, this, "");

    private TOvercurrentProtectionElements(Name alias, Table<TOvercurrentProtectionElementsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TOvercurrentProtectionElements(Name alias, Table<TOvercurrentProtectionElementsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_overcurrent_protection_elements</code>
     * table reference
     */
    public TOvercurrentProtectionElements(String alias) {
        this(DSL.name(alias), T_OVERCURRENT_PROTECTION_ELEMENTS);
    }

    /**
     * Create an aliased <code>public.t_overcurrent_protection_elements</code>
     * table reference
     */
    public TOvercurrentProtectionElements(Name alias) {
        this(alias, T_OVERCURRENT_PROTECTION_ELEMENTS);
    }

    /**
     * Create a <code>public.t_overcurrent_protection_elements</code> table
     * reference
     */
    public TOvercurrentProtectionElements() {
        this(DSL.name("t_overcurrent_protection_elements"), null);
    }

    public <O extends Record> TOvercurrentProtectionElements(Table<O> path, ForeignKey<O, TOvercurrentProtectionElementsRecord> childPath, InverseForeignKey<O, TOvercurrentProtectionElementsRecord> parentPath) {
        super(path, childPath, parentPath, T_OVERCURRENT_PROTECTION_ELEMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TOvercurrentProtectionElementsPath extends TOvercurrentProtectionElements implements Path<TOvercurrentProtectionElementsRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> TOvercurrentProtectionElementsPath(Table<O> path, ForeignKey<O, TOvercurrentProtectionElementsRecord> childPath, InverseForeignKey<O, TOvercurrentProtectionElementsRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private TOvercurrentProtectionElementsPath(Name alias, Table<TOvercurrentProtectionElementsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TOvercurrentProtectionElementsPath as(String alias) {
            return new TOvercurrentProtectionElementsPath(DSL.name(alias), this);
        }

        @Override
        public TOvercurrentProtectionElementsPath as(Name alias) {
            return new TOvercurrentProtectionElementsPath(alias, this);
        }

        @Override
        public TOvercurrentProtectionElementsPath as(Table<?> alias) {
            return new TOvercurrentProtectionElementsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TOvercurrentProtectionElementsRecord> getPrimaryKey() {
        return Keys.T_OVERCURRENT_PROTECTION_ELEMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<TOvercurrentProtectionElementsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_OVERCURRENT_PROTECTION_ELEMENTS__FK6V1F3VVYO6I0LIU7VWPDE4SIQ);
    }

    private transient TProjectsPath _tProjects;

    /**
     * Get the implicit join path to the <code>public.t_projects</code> table.
     */
    public TProjectsPath tProjects() {
        if (_tProjects == null)
            _tProjects = new TProjectsPath(this, Keys.T_OVERCURRENT_PROTECTION_ELEMENTS__FK6V1F3VVYO6I0LIU7VWPDE4SIQ, null);

        return _tProjects;
    }

    @Override
    public TOvercurrentProtectionElements as(String alias) {
        return new TOvercurrentProtectionElements(DSL.name(alias), this);
    }

    @Override
    public TOvercurrentProtectionElements as(Name alias) {
        return new TOvercurrentProtectionElements(alias, this);
    }

    @Override
    public TOvercurrentProtectionElements as(Table<?> alias) {
        return new TOvercurrentProtectionElements(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TOvercurrentProtectionElements rename(String name) {
        return new TOvercurrentProtectionElements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TOvercurrentProtectionElements rename(Name name) {
        return new TOvercurrentProtectionElements(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TOvercurrentProtectionElements rename(Table<?> name) {
        return new TOvercurrentProtectionElements(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElements where(Condition condition) {
        return new TOvercurrentProtectionElements(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElements where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElements where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElements where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElements where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElements where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElements where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TOvercurrentProtectionElements where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElements whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TOvercurrentProtectionElements whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
