/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.Revinfo.RevinfoPath;
import pl.dabrowski.electrotools.jooq.tables.records.TProjectsAudRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TProjectsAud extends TableImpl<TProjectsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_projects_aud</code>
     */
    public static final TProjectsAud T_PROJECTS_AUD = new TProjectsAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TProjectsAudRecord> getRecordType() {
        return TProjectsAudRecord.class;
    }

    /**
     * The column <code>public.t_projects_aud.id</code>.
     */
    public final TableField<TProjectsAudRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_projects_aud.rev</code>.
     */
    public final TableField<TProjectsAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.t_projects_aud.revtype</code>.
     */
    public final TableField<TProjectsAudRecord, Short> REVTYPE = createField(DSL.name("revtype"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.t_projects_aud.created_by</code>.
     */
    public final TableField<TProjectsAudRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_projects_aud.created_date</code>.
     */
    public final TableField<TProjectsAudRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_projects_aud.modified_by</code>.
     */
    public final TableField<TProjectsAudRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_projects_aud.modified_date</code>.
     */
    public final TableField<TProjectsAudRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_projects_aud.name</code>.
     */
    public final TableField<TProjectsAudRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_projects_aud.owner</code>.
     */
    public final TableField<TProjectsAudRecord, String> OWNER = createField(DSL.name("owner"), SQLDataType.VARCHAR(255), this, "");

    private TProjectsAud(Name alias, Table<TProjectsAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TProjectsAud(Name alias, Table<TProjectsAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_projects_aud</code> table reference
     */
    public TProjectsAud(String alias) {
        this(DSL.name(alias), T_PROJECTS_AUD);
    }

    /**
     * Create an aliased <code>public.t_projects_aud</code> table reference
     */
    public TProjectsAud(Name alias) {
        this(alias, T_PROJECTS_AUD);
    }

    /**
     * Create a <code>public.t_projects_aud</code> table reference
     */
    public TProjectsAud() {
        this(DSL.name("t_projects_aud"), null);
    }

    public <O extends Record> TProjectsAud(Table<O> path, ForeignKey<O, TProjectsAudRecord> childPath, InverseForeignKey<O, TProjectsAudRecord> parentPath) {
        super(path, childPath, parentPath, T_PROJECTS_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TProjectsAudPath extends TProjectsAud implements Path<TProjectsAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TProjectsAudPath(Table<O> path, ForeignKey<O, TProjectsAudRecord> childPath, InverseForeignKey<O, TProjectsAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TProjectsAudPath(Name alias, Table<TProjectsAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TProjectsAudPath as(String alias) {
            return new TProjectsAudPath(DSL.name(alias), this);
        }

        @Override
        public TProjectsAudPath as(Name alias) {
            return new TProjectsAudPath(alias, this);
        }

        @Override
        public TProjectsAudPath as(Table<?> alias) {
            return new TProjectsAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TProjectsAudRecord> getPrimaryKey() {
        return Keys.T_PROJECTS_AUD_PKEY;
    }

    @Override
    public List<ForeignKey<TProjectsAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_PROJECTS_AUD__FKCSISWK63MJ80MHBXGM7SYYIMW);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>public.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.T_PROJECTS_AUD__FKCSISWK63MJ80MHBXGM7SYYIMW, null);

        return _revinfo;
    }

    @Override
    public TProjectsAud as(String alias) {
        return new TProjectsAud(DSL.name(alias), this);
    }

    @Override
    public TProjectsAud as(Name alias) {
        return new TProjectsAud(alias, this);
    }

    @Override
    public TProjectsAud as(Table<?> alias) {
        return new TProjectsAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TProjectsAud rename(String name) {
        return new TProjectsAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TProjectsAud rename(Name name) {
        return new TProjectsAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TProjectsAud rename(Table<?> name) {
        return new TProjectsAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjectsAud where(Condition condition) {
        return new TProjectsAud(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjectsAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjectsAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjectsAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjectsAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjectsAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjectsAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjectsAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjectsAud whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjectsAud whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
