/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.TBasicElements.TBasicElementsPath;
import pl.dabrowski.electrotools.jooq.tables.TLoadElements.TLoadElementsPath;
import pl.dabrowski.electrotools.jooq.tables.TOvercurrentProtectionElements.TOvercurrentProtectionElementsPath;
import pl.dabrowski.electrotools.jooq.tables.TRcdElements.TRcdElementsPath;
import pl.dabrowski.electrotools.jooq.tables.TTerminalElements.TTerminalElementsPath;
import pl.dabrowski.electrotools.jooq.tables.records.TProjectsRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TProjects extends TableImpl<TProjectsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_projects</code>
     */
    public static final TProjects T_PROJECTS = new TProjects();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TProjectsRecord> getRecordType() {
        return TProjectsRecord.class;
    }

    /**
     * The column <code>public.t_projects.id</code>.
     */
    public final TableField<TProjectsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_projects.created_by</code>.
     */
    public final TableField<TProjectsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_projects.created_date</code>.
     */
    public final TableField<TProjectsRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_projects.modified_by</code>.
     */
    public final TableField<TProjectsRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_projects.modified_date</code>.
     */
    public final TableField<TProjectsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_projects.name</code>.
     */
    public final TableField<TProjectsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_projects.owner</code>.
     */
    public final TableField<TProjectsRecord, String> OWNER = createField(DSL.name("owner"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_projects.version</code>.
     */
    public final TableField<TProjectsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    private TProjects(Name alias, Table<TProjectsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TProjects(Name alias, Table<TProjectsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_projects</code> table reference
     */
    public TProjects(String alias) {
        this(DSL.name(alias), T_PROJECTS);
    }

    /**
     * Create an aliased <code>public.t_projects</code> table reference
     */
    public TProjects(Name alias) {
        this(alias, T_PROJECTS);
    }

    /**
     * Create a <code>public.t_projects</code> table reference
     */
    public TProjects() {
        this(DSL.name("t_projects"), null);
    }

    public <O extends Record> TProjects(Table<O> path, ForeignKey<O, TProjectsRecord> childPath, InverseForeignKey<O, TProjectsRecord> parentPath) {
        super(path, childPath, parentPath, T_PROJECTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TProjectsPath extends TProjects implements Path<TProjectsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TProjectsPath(Table<O> path, ForeignKey<O, TProjectsRecord> childPath, InverseForeignKey<O, TProjectsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TProjectsPath(Name alias, Table<TProjectsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TProjectsPath as(String alias) {
            return new TProjectsPath(DSL.name(alias), this);
        }

        @Override
        public TProjectsPath as(Name alias) {
            return new TProjectsPath(alias, this);
        }

        @Override
        public TProjectsPath as(Table<?> alias) {
            return new TProjectsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TProjectsRecord> getPrimaryKey() {
        return Keys.T_PROJECTS_PKEY;
    }

    private transient TTerminalElementsPath _tTerminalElements;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_terminal_elements</code> table
     */
    public TTerminalElementsPath tTerminalElements() {
        if (_tTerminalElements == null)
            _tTerminalElements = new TTerminalElementsPath(this, null, Keys.T_TERMINAL_ELEMENTS__FK2V3SAU5EQ0U5C735G5INPCVVU.getInverseKey());

        return _tTerminalElements;
    }

    private transient TBasicElementsPath _tBasicElements;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_basic_elements</code> table
     */
    public TBasicElementsPath tBasicElements() {
        if (_tBasicElements == null)
            _tBasicElements = new TBasicElementsPath(this, null, Keys.T_BASIC_ELEMENTS__FK39DHW07WI5ST8PSYYUTES9193.getInverseKey());

        return _tBasicElements;
    }

    private transient TOvercurrentProtectionElementsPath _tOvercurrentProtectionElements;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_overcurrent_protection_elements</code> table
     */
    public TOvercurrentProtectionElementsPath tOvercurrentProtectionElements() {
        if (_tOvercurrentProtectionElements == null)
            _tOvercurrentProtectionElements = new TOvercurrentProtectionElementsPath(this, null, Keys.T_OVERCURRENT_PROTECTION_ELEMENTS__FK6V1F3VVYO6I0LIU7VWPDE4SIQ.getInverseKey());

        return _tOvercurrentProtectionElements;
    }

    private transient TRcdElementsPath _tRcdElements;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_rcd_elements</code> table
     */
    public TRcdElementsPath tRcdElements() {
        if (_tRcdElements == null)
            _tRcdElements = new TRcdElementsPath(this, null, Keys.T_RCD_ELEMENTS__FK74KAHOI0V42OTL9B42G55TH8G.getInverseKey());

        return _tRcdElements;
    }

    private transient TLoadElementsPath _tLoadElements;

    /**
     * Get the implicit to-many join path to the
     * <code>public.t_load_elements</code> table
     */
    public TLoadElementsPath tLoadElements() {
        if (_tLoadElements == null)
            _tLoadElements = new TLoadElementsPath(this, null, Keys.T_LOAD_ELEMENTS__FKAOPRM7AO3HVQ1QIIAD64VX71O.getInverseKey());

        return _tLoadElements;
    }

    @Override
    public TProjects as(String alias) {
        return new TProjects(DSL.name(alias), this);
    }

    @Override
    public TProjects as(Name alias) {
        return new TProjects(alias, this);
    }

    @Override
    public TProjects as(Table<?> alias) {
        return new TProjects(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TProjects rename(String name) {
        return new TProjects(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TProjects rename(Name name) {
        return new TProjects(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TProjects rename(Table<?> name) {
        return new TProjects(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjects where(Condition condition) {
        return new TProjects(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjects where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjects where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjects where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjects where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjects where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjects where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TProjects where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjects whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TProjects whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
