/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.Revinfo.RevinfoPath;
import pl.dabrowski.electrotools.jooq.tables.records.TRcdElementsAudRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TRcdElementsAud extends TableImpl<TRcdElementsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_rcd_elements_aud</code>
     */
    public static final TRcdElementsAud T_RCD_ELEMENTS_AUD = new TRcdElementsAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRcdElementsAudRecord> getRecordType() {
        return TRcdElementsAudRecord.class;
    }

    /**
     * The column <code>public.t_rcd_elements_aud.id</code>.
     */
    public final TableField<TRcdElementsAudRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_rcd_elements_aud.rev</code>.
     */
    public final TableField<TRcdElementsAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.t_rcd_elements_aud.revtype</code>.
     */
    public final TableField<TRcdElementsAudRecord, Short> REVTYPE = createField(DSL.name("revtype"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.t_rcd_elements_aud.diff_current</code>.
     */
    public final TableField<TRcdElementsAudRecord, Integer> DIFF_CURRENT = createField(DSL.name("diff_current"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_rcd_elements_aud.nominal_current</code>.
     */
    public final TableField<TRcdElementsAudRecord, Integer> NOMINAL_CURRENT = createField(DSL.name("nominal_current"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_rcd_elements_aud.pole_number</code>.
     */
    public final TableField<TRcdElementsAudRecord, Integer> POLE_NUMBER = createField(DSL.name("pole_number"), SQLDataType.INTEGER, this, "");

    private TRcdElementsAud(Name alias, Table<TRcdElementsAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TRcdElementsAud(Name alias, Table<TRcdElementsAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_rcd_elements_aud</code> table reference
     */
    public TRcdElementsAud(String alias) {
        this(DSL.name(alias), T_RCD_ELEMENTS_AUD);
    }

    /**
     * Create an aliased <code>public.t_rcd_elements_aud</code> table reference
     */
    public TRcdElementsAud(Name alias) {
        this(alias, T_RCD_ELEMENTS_AUD);
    }

    /**
     * Create a <code>public.t_rcd_elements_aud</code> table reference
     */
    public TRcdElementsAud() {
        this(DSL.name("t_rcd_elements_aud"), null);
    }

    public <O extends Record> TRcdElementsAud(Table<O> path, ForeignKey<O, TRcdElementsAudRecord> childPath, InverseForeignKey<O, TRcdElementsAudRecord> parentPath) {
        super(path, childPath, parentPath, T_RCD_ELEMENTS_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TRcdElementsAudPath extends TRcdElementsAud implements Path<TRcdElementsAudRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> TRcdElementsAudPath(Table<O> path, ForeignKey<O, TRcdElementsAudRecord> childPath, InverseForeignKey<O, TRcdElementsAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private TRcdElementsAudPath(Name alias, Table<TRcdElementsAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TRcdElementsAudPath as(String alias) {
            return new TRcdElementsAudPath(DSL.name(alias), this);
        }

        @Override
        public TRcdElementsAudPath as(Name alias) {
            return new TRcdElementsAudPath(alias, this);
        }

        @Override
        public TRcdElementsAudPath as(Table<?> alias) {
            return new TRcdElementsAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TRcdElementsAudRecord> getPrimaryKey() {
        return Keys.T_RCD_ELEMENTS_AUD_PKEY;
    }

    @Override
    public List<ForeignKey<TRcdElementsAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_RCD_ELEMENTS_AUD__FKH6KI2JI6DG3BTUM8SHEMS7ES);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>public.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.T_RCD_ELEMENTS_AUD__FKH6KI2JI6DG3BTUM8SHEMS7ES, null);

        return _revinfo;
    }

    @Override
    public TRcdElementsAud as(String alias) {
        return new TRcdElementsAud(DSL.name(alias), this);
    }

    @Override
    public TRcdElementsAud as(Name alias) {
        return new TRcdElementsAud(alias, this);
    }

    @Override
    public TRcdElementsAud as(Table<?> alias) {
        return new TRcdElementsAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcdElementsAud rename(String name) {
        return new TRcdElementsAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcdElementsAud rename(Name name) {
        return new TRcdElementsAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcdElementsAud rename(Table<?> name) {
        return new TRcdElementsAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElementsAud where(Condition condition) {
        return new TRcdElementsAud(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElementsAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElementsAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElementsAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElementsAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElementsAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElementsAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElementsAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElementsAud whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElementsAud whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
