/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.TProjects.TProjectsPath;
import pl.dabrowski.electrotools.jooq.tables.records.TRcdElementsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TRcdElements extends TableImpl<TRcdElementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_rcd_elements</code>
     */
    public static final TRcdElements T_RCD_ELEMENTS = new TRcdElements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TRcdElementsRecord> getRecordType() {
        return TRcdElementsRecord.class;
    }

    /**
     * The column <code>public.t_rcd_elements.id</code>.
     */
    public final TableField<TRcdElementsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_rcd_elements.created_by</code>.
     */
    public final TableField<TRcdElementsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_rcd_elements.created_date</code>.
     */
    public final TableField<TRcdElementsRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_rcd_elements.modified_by</code>.
     */
    public final TableField<TRcdElementsRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_rcd_elements.modified_date</code>.
     */
    public final TableField<TRcdElementsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_rcd_elements.version</code>.
     */
    public final TableField<TRcdElementsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_rcd_elements.label</code>.
     */
    public final TableField<TRcdElementsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_rcd_elements.parent_id</code>.
     */
    public final TableField<TRcdElementsRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.t_rcd_elements.diameter</code>.
     */
    public final TableField<TRcdElementsRecord, String> DIAMETER = createField(DSL.name("diameter"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_rcd_elements.length</code>.
     */
    public final TableField<TRcdElementsRecord, Double> LENGTH = createField(DSL.name("length"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_rcd_elements.phase</code>.
     */
    public final TableField<TRcdElementsRecord, String> PHASE = createField(DSL.name("phase"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_rcd_elements.placement</code>.
     */
    public final TableField<TRcdElementsRecord, String> PLACEMENT = createField(DSL.name("placement"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_rcd_elements.wire_type</code>.
     */
    public final TableField<TRcdElementsRecord, String> WIRE_TYPE = createField(DSL.name("wire_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_rcd_elements.x</code>.
     */
    public final TableField<TRcdElementsRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_rcd_elements.y</code>.
     */
    public final TableField<TRcdElementsRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_rcd_elements.diff_current</code>.
     */
    public final TableField<TRcdElementsRecord, Integer> DIFF_CURRENT = createField(DSL.name("diff_current"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_rcd_elements.nominal_current</code>.
     */
    public final TableField<TRcdElementsRecord, Integer> NOMINAL_CURRENT = createField(DSL.name("nominal_current"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_rcd_elements.pole_number</code>.
     */
    public final TableField<TRcdElementsRecord, Integer> POLE_NUMBER = createField(DSL.name("pole_number"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_rcd_elements.project_id</code>.
     */
    public final TableField<TRcdElementsRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID, this, "");

    private TRcdElements(Name alias, Table<TRcdElementsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TRcdElements(Name alias, Table<TRcdElementsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_rcd_elements</code> table reference
     */
    public TRcdElements(String alias) {
        this(DSL.name(alias), T_RCD_ELEMENTS);
    }

    /**
     * Create an aliased <code>public.t_rcd_elements</code> table reference
     */
    public TRcdElements(Name alias) {
        this(alias, T_RCD_ELEMENTS);
    }

    /**
     * Create a <code>public.t_rcd_elements</code> table reference
     */
    public TRcdElements() {
        this(DSL.name("t_rcd_elements"), null);
    }

    public <O extends Record> TRcdElements(Table<O> path, ForeignKey<O, TRcdElementsRecord> childPath, InverseForeignKey<O, TRcdElementsRecord> parentPath) {
        super(path, childPath, parentPath, T_RCD_ELEMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TRcdElementsPath extends TRcdElements implements Path<TRcdElementsRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> TRcdElementsPath(Table<O> path, ForeignKey<O, TRcdElementsRecord> childPath, InverseForeignKey<O, TRcdElementsRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private TRcdElementsPath(Name alias, Table<TRcdElementsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TRcdElementsPath as(String alias) {
            return new TRcdElementsPath(DSL.name(alias), this);
        }

        @Override
        public TRcdElementsPath as(Name alias) {
            return new TRcdElementsPath(alias, this);
        }

        @Override
        public TRcdElementsPath as(Table<?> alias) {
            return new TRcdElementsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TRcdElementsRecord> getPrimaryKey() {
        return Keys.T_RCD_ELEMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<TRcdElementsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_RCD_ELEMENTS__FK74KAHOI0V42OTL9B42G55TH8G);
    }

    private transient TProjectsPath _tProjects;

    /**
     * Get the implicit join path to the <code>public.t_projects</code> table.
     */
    public TProjectsPath tProjects() {
        if (_tProjects == null)
            _tProjects = new TProjectsPath(this, Keys.T_RCD_ELEMENTS__FK74KAHOI0V42OTL9B42G55TH8G, null);

        return _tProjects;
    }

    @Override
    public TRcdElements as(String alias) {
        return new TRcdElements(DSL.name(alias), this);
    }

    @Override
    public TRcdElements as(Name alias) {
        return new TRcdElements(alias, this);
    }

    @Override
    public TRcdElements as(Table<?> alias) {
        return new TRcdElements(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcdElements rename(String name) {
        return new TRcdElements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcdElements rename(Name name) {
        return new TRcdElements(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TRcdElements rename(Table<?> name) {
        return new TRcdElements(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElements where(Condition condition) {
        return new TRcdElements(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElements where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElements where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElements where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElements where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElements where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElements where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TRcdElements where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElements whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TRcdElements whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
