/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.TProjects.TProjectsPath;
import pl.dabrowski.electrotools.jooq.tables.records.TTerminalElementsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TTerminalElements extends TableImpl<TTerminalElementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_terminal_elements</code>
     */
    public static final TTerminalElements T_TERMINAL_ELEMENTS = new TTerminalElements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TTerminalElementsRecord> getRecordType() {
        return TTerminalElementsRecord.class;
    }

    /**
     * The column <code>public.t_terminal_elements.id</code>.
     */
    public final TableField<TTerminalElementsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_terminal_elements.created_by</code>.
     */
    public final TableField<TTerminalElementsRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_terminal_elements.created_date</code>.
     */
    public final TableField<TTerminalElementsRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_terminal_elements.modified_by</code>.
     */
    public final TableField<TTerminalElementsRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_terminal_elements.modified_date</code>.
     */
    public final TableField<TTerminalElementsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.t_terminal_elements.version</code>.
     */
    public final TableField<TTerminalElementsRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_terminal_elements.label</code>.
     */
    public final TableField<TTerminalElementsRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_terminal_elements.parent_id</code>.
     */
    public final TableField<TTerminalElementsRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.t_terminal_elements.diameter</code>.
     */
    public final TableField<TTerminalElementsRecord, String> DIAMETER = createField(DSL.name("diameter"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_terminal_elements.length</code>.
     */
    public final TableField<TTerminalElementsRecord, Double> LENGTH = createField(DSL.name("length"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_terminal_elements.phase</code>.
     */
    public final TableField<TTerminalElementsRecord, String> PHASE = createField(DSL.name("phase"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_terminal_elements.placement</code>.
     */
    public final TableField<TTerminalElementsRecord, String> PLACEMENT = createField(DSL.name("placement"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_terminal_elements.wire_type</code>.
     */
    public final TableField<TTerminalElementsRecord, String> WIRE_TYPE = createField(DSL.name("wire_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.t_terminal_elements.x</code>.
     */
    public final TableField<TTerminalElementsRecord, Double> X = createField(DSL.name("x"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_terminal_elements.y</code>.
     */
    public final TableField<TTerminalElementsRecord, Double> Y = createField(DSL.name("y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.t_terminal_elements.type</code>.
     */
    public final TableField<TTerminalElementsRecord, Integer> TYPE = createField(DSL.name("type"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.t_terminal_elements.project_id</code>.
     */
    public final TableField<TTerminalElementsRecord, UUID> PROJECT_ID = createField(DSL.name("project_id"), SQLDataType.UUID, this, "");

    private TTerminalElements(Name alias, Table<TTerminalElementsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TTerminalElements(Name alias, Table<TTerminalElementsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_terminal_elements</code> table reference
     */
    public TTerminalElements(String alias) {
        this(DSL.name(alias), T_TERMINAL_ELEMENTS);
    }

    /**
     * Create an aliased <code>public.t_terminal_elements</code> table reference
     */
    public TTerminalElements(Name alias) {
        this(alias, T_TERMINAL_ELEMENTS);
    }

    /**
     * Create a <code>public.t_terminal_elements</code> table reference
     */
    public TTerminalElements() {
        this(DSL.name("t_terminal_elements"), null);
    }

    public <O extends Record> TTerminalElements(Table<O> path, ForeignKey<O, TTerminalElementsRecord> childPath, InverseForeignKey<O, TTerminalElementsRecord> parentPath) {
        super(path, childPath, parentPath, T_TERMINAL_ELEMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TTerminalElementsPath extends TTerminalElements implements Path<TTerminalElementsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TTerminalElementsPath(Table<O> path, ForeignKey<O, TTerminalElementsRecord> childPath, InverseForeignKey<O, TTerminalElementsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TTerminalElementsPath(Name alias, Table<TTerminalElementsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TTerminalElementsPath as(String alias) {
            return new TTerminalElementsPath(DSL.name(alias), this);
        }

        @Override
        public TTerminalElementsPath as(Name alias) {
            return new TTerminalElementsPath(alias, this);
        }

        @Override
        public TTerminalElementsPath as(Table<?> alias) {
            return new TTerminalElementsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TTerminalElementsRecord> getPrimaryKey() {
        return Keys.T_TERMINAL_ELEMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<TTerminalElementsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_TERMINAL_ELEMENTS__FK2V3SAU5EQ0U5C735G5INPCVVU);
    }

    private transient TProjectsPath _tProjects;

    /**
     * Get the implicit join path to the <code>public.t_projects</code> table.
     */
    public TProjectsPath tProjects() {
        if (_tProjects == null)
            _tProjects = new TProjectsPath(this, Keys.T_TERMINAL_ELEMENTS__FK2V3SAU5EQ0U5C735G5INPCVVU, null);

        return _tProjects;
    }

    @Override
    public TTerminalElements as(String alias) {
        return new TTerminalElements(DSL.name(alias), this);
    }

    @Override
    public TTerminalElements as(Name alias) {
        return new TTerminalElements(alias, this);
    }

    @Override
    public TTerminalElements as(Table<?> alias) {
        return new TTerminalElements(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TTerminalElements rename(String name) {
        return new TTerminalElements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTerminalElements rename(Name name) {
        return new TTerminalElements(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTerminalElements rename(Table<?> name) {
        return new TTerminalElements(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElements where(Condition condition) {
        return new TTerminalElements(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElements where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElements where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElements where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElements where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElements where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElements where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElements where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElements whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElements whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
