/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables;


import org.jooq.*;
import org.jooq.Record;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.dabrowski.electrotools.jooq.Keys;
import pl.dabrowski.electrotools.jooq.Public;
import pl.dabrowski.electrotools.jooq.tables.Revinfo.RevinfoPath;
import pl.dabrowski.electrotools.jooq.tables.records.TTerminalElementsAudRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TTerminalElementsAud extends TableImpl<TTerminalElementsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.t_terminal_elements_aud</code>
     */
    public static final TTerminalElementsAud T_TERMINAL_ELEMENTS_AUD = new TTerminalElementsAud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TTerminalElementsAudRecord> getRecordType() {
        return TTerminalElementsAudRecord.class;
    }

    /**
     * The column <code>public.t_terminal_elements_aud.id</code>.
     */
    public final TableField<TTerminalElementsAudRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.t_terminal_elements_aud.rev</code>.
     */
    public final TableField<TTerminalElementsAudRecord, Integer> REV = createField(DSL.name("rev"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.t_terminal_elements_aud.revtype</code>.
     */
    public final TableField<TTerminalElementsAudRecord, Short> REVTYPE = createField(DSL.name("revtype"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.t_terminal_elements_aud.type</code>.
     */
    public final TableField<TTerminalElementsAudRecord, Integer> TYPE = createField(DSL.name("type"), SQLDataType.INTEGER, this, "");

    private TTerminalElementsAud(Name alias, Table<TTerminalElementsAudRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TTerminalElementsAud(Name alias, Table<TTerminalElementsAudRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.t_terminal_elements_aud</code> table
     * reference
     */
    public TTerminalElementsAud(String alias) {
        this(DSL.name(alias), T_TERMINAL_ELEMENTS_AUD);
    }

    /**
     * Create an aliased <code>public.t_terminal_elements_aud</code> table
     * reference
     */
    public TTerminalElementsAud(Name alias) {
        this(alias, T_TERMINAL_ELEMENTS_AUD);
    }

    /**
     * Create a <code>public.t_terminal_elements_aud</code> table reference
     */
    public TTerminalElementsAud() {
        this(DSL.name("t_terminal_elements_aud"), null);
    }

    public <O extends Record> TTerminalElementsAud(Table<O> path, ForeignKey<O, TTerminalElementsAudRecord> childPath, InverseForeignKey<O, TTerminalElementsAudRecord> parentPath) {
        super(path, childPath, parentPath, T_TERMINAL_ELEMENTS_AUD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TTerminalElementsAudPath extends TTerminalElementsAud implements Path<TTerminalElementsAudRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TTerminalElementsAudPath(Table<O> path, ForeignKey<O, TTerminalElementsAudRecord> childPath, InverseForeignKey<O, TTerminalElementsAudRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TTerminalElementsAudPath(Name alias, Table<TTerminalElementsAudRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TTerminalElementsAudPath as(String alias) {
            return new TTerminalElementsAudPath(DSL.name(alias), this);
        }

        @Override
        public TTerminalElementsAudPath as(Name alias) {
            return new TTerminalElementsAudPath(alias, this);
        }

        @Override
        public TTerminalElementsAudPath as(Table<?> alias) {
            return new TTerminalElementsAudPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TTerminalElementsAudRecord> getPrimaryKey() {
        return Keys.T_TERMINAL_ELEMENTS_AUD_PKEY;
    }

    @Override
    public List<ForeignKey<TTerminalElementsAudRecord, ?>> getReferences() {
        return Arrays.asList(Keys.T_TERMINAL_ELEMENTS_AUD__FKIB9TINNVJAKFN4WRC7N877FTJ);
    }

    private transient RevinfoPath _revinfo;

    /**
     * Get the implicit join path to the <code>public.revinfo</code> table.
     */
    public RevinfoPath revinfo() {
        if (_revinfo == null)
            _revinfo = new RevinfoPath(this, Keys.T_TERMINAL_ELEMENTS_AUD__FKIB9TINNVJAKFN4WRC7N877FTJ, null);

        return _revinfo;
    }

    @Override
    public TTerminalElementsAud as(String alias) {
        return new TTerminalElementsAud(DSL.name(alias), this);
    }

    @Override
    public TTerminalElementsAud as(Name alias) {
        return new TTerminalElementsAud(alias, this);
    }

    @Override
    public TTerminalElementsAud as(Table<?> alias) {
        return new TTerminalElementsAud(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TTerminalElementsAud rename(String name) {
        return new TTerminalElementsAud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTerminalElementsAud rename(Name name) {
        return new TTerminalElementsAud(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTerminalElementsAud rename(Table<?> name) {
        return new TTerminalElementsAud(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElementsAud where(Condition condition) {
        return new TTerminalElementsAud(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElementsAud where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElementsAud where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElementsAud where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElementsAud where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElementsAud where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElementsAud where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TTerminalElementsAud where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElementsAud whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TTerminalElementsAud whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
