/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import pl.dabrowski.electrotools.jooq.tables.Revinfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class RevinfoRecord extends UpdatableRecordImpl<RevinfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.revinfo.rev</code>.
     */
    public void setRev(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.revinfo.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.revinfo.revtstmp</code>.
     */
    public void setRevtstmp(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.revinfo.revtstmp</code>.
     */
    public Long getRevtstmp() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RevinfoRecord
     */
    public RevinfoRecord() {
        super(Revinfo.REVINFO);
    }

    /**
     * Create a detached, initialised RevinfoRecord
     */
    public RevinfoRecord(Integer rev, Long revtstmp) {
        super(Revinfo.REVINFO);

        setRev(rev);
        setRevtstmp(revtstmp);
        resetTouchedOnNotNull();
    }
}
