/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import pl.dabrowski.electrotools.jooq.tables.TLoadElements;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TLoadElementsRecord extends UpdatableRecordImpl<TLoadElementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_load_elements.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_load_elements.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.t_load_elements.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_load_elements.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_load_elements.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_load_elements.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.t_load_elements.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_load_elements.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_load_elements.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_load_elements.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.t_load_elements.version</code>.
     */
    public void setVersion(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_load_elements.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.t_load_elements.label</code>.
     */
    public void setLabel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_load_elements.label</code>.
     */
    public String getLabel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.t_load_elements.parent_id</code>.
     */
    public void setParentId(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_load_elements.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.t_load_elements.diameter</code>.
     */
    public void setDiameter(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_load_elements.diameter</code>.
     */
    public String getDiameter() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.t_load_elements.length</code>.
     */
    public void setLength(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_load_elements.length</code>.
     */
    public Double getLength() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.t_load_elements.phase</code>.
     */
    public void setPhase(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_load_elements.phase</code>.
     */
    public String getPhase() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.t_load_elements.placement</code>.
     */
    public void setPlacement(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_load_elements.placement</code>.
     */
    public String getPlacement() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.t_load_elements.wire_type</code>.
     */
    public void setWireType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_load_elements.wire_type</code>.
     */
    public String getWireType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.t_load_elements.x</code>.
     */
    public void setX(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_load_elements.x</code>.
     */
    public Double getX() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.t_load_elements.y</code>.
     */
    public void setY(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.t_load_elements.y</code>.
     */
    public Double getY() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.t_load_elements.config</code>.
     */
    public void setConfig(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.t_load_elements.config</code>.
     */
    public String getConfig() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.t_load_elements.draw_power</code>.
     */
    public void setDrawPower(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.t_load_elements.draw_power</code>.
     */
    public Double getDrawPower() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.t_load_elements.high_start_current</code>.
     */
    public void setHighStartCurrent(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.t_load_elements.high_start_current</code>.
     */
    public Boolean getHighStartCurrent() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>public.t_load_elements.power_factor</code>.
     */
    public void setPowerFactor(Double value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.t_load_elements.power_factor</code>.
     */
    public Double getPowerFactor() {
        return (Double) get(18);
    }

    /**
     * Setter for <code>public.t_load_elements.zeroed</code>.
     */
    public void setZeroed(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.t_load_elements.zeroed</code>.
     */
    public Boolean getZeroed() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>public.t_load_elements.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.t_load_elements.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLoadElementsRecord
     */
    public TLoadElementsRecord() {
        super(TLoadElements.T_LOAD_ELEMENTS);
    }

    /**
     * Create a detached, initialised TLoadElementsRecord
     */
    public TLoadElementsRecord(UUID id, String createdBy, LocalDateTime createdDate, String modifiedBy, LocalDateTime modifiedDate, Integer version, String label, UUID parentId, String diameter, Double length, String phase, String placement, String wireType, Double x, Double y, String config, Double drawPower, Boolean highStartCurrent, Double powerFactor, Boolean zeroed, UUID projectId) {
        super(TLoadElements.T_LOAD_ELEMENTS);

        setId(id);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setVersion(version);
        setLabel(label);
        setParentId(parentId);
        setDiameter(diameter);
        setLength(length);
        setPhase(phase);
        setPlacement(placement);
        setWireType(wireType);
        setX(x);
        setY(y);
        setConfig(config);
        setDrawPower(drawPower);
        setHighStartCurrent(highStartCurrent);
        setPowerFactor(powerFactor);
        setZeroed(zeroed);
        setProjectId(projectId);
        resetTouchedOnNotNull();
    }
}
