/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import pl.dabrowski.electrotools.jooq.tables.TLoadElementsAud;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TLoadElementsAudRecord extends UpdatableRecordImpl<TLoadElementsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_load_elements_aud.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.t_load_elements_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.t_load_elements_aud.revtype</code>.
     */
    public void setRevtype(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.revtype</code>.
     */
    public Short getRevtype() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.t_load_elements_aud.config</code>.
     */
    public void setConfig(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.config</code>.
     */
    public String getConfig() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_load_elements_aud.draw_power</code>.
     */
    public void setDrawPower(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.draw_power</code>.
     */
    public Double getDrawPower() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.t_load_elements_aud.high_start_current</code>.
     */
    public void setHighStartCurrent(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.high_start_current</code>.
     */
    public Boolean getHighStartCurrent() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.t_load_elements_aud.power_factor</code>.
     */
    public void setPowerFactor(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.power_factor</code>.
     */
    public Double getPowerFactor() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.t_load_elements_aud.zeroed</code>.
     */
    public void setZeroed(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_load_elements_aud.zeroed</code>.
     */
    public Boolean getZeroed() {
        return (Boolean) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TLoadElementsAudRecord
     */
    public TLoadElementsAudRecord() {
        super(TLoadElementsAud.T_LOAD_ELEMENTS_AUD);
    }

    /**
     * Create a detached, initialised TLoadElementsAudRecord
     */
    public TLoadElementsAudRecord(UUID id, Integer rev, Short revtype, String config, Double drawPower, Boolean highStartCurrent, Double powerFactor, Boolean zeroed) {
        super(TLoadElementsAud.T_LOAD_ELEMENTS_AUD);

        setId(id);
        setRev(rev);
        setRevtype(revtype);
        setConfig(config);
        setDrawPower(drawPower);
        setHighStartCurrent(highStartCurrent);
        setPowerFactor(powerFactor);
        setZeroed(zeroed);
        resetTouchedOnNotNull();
    }
}
