/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import pl.dabrowski.electrotools.jooq.tables.TOvercurrentProtectionElementsAud;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TOvercurrentProtectionElementsAudRecord extends UpdatableRecordImpl<TOvercurrentProtectionElementsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_overcurrent_protection_elements_aud.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_overcurrent_protection_elements_aud.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.t_overcurrent_protection_elements_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_overcurrent_protection_elements_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>public.t_overcurrent_protection_elements_aud.revtype</code>.
     */
    public void setRevtype(Short value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.t_overcurrent_protection_elements_aud.revtype</code>.
     */
    public Short getRevtype() {
        return (Short) get(2);
    }

    /**
     * Setter for
     * <code>public.t_overcurrent_protection_elements_aud.amperage</code>.
     */
    public void setAmperage(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.t_overcurrent_protection_elements_aud.amperage</code>.
     */
    public Integer getAmperage() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>public.t_overcurrent_protection_elements_aud.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.t_overcurrent_protection_elements_aud.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TOvercurrentProtectionElementsAudRecord
     */
    public TOvercurrentProtectionElementsAudRecord() {
        super(TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD);
    }

    /**
     * Create a detached, initialised TOvercurrentProtectionElementsAudRecord
     */
    public TOvercurrentProtectionElementsAudRecord(UUID id, Integer rev, Short revtype, Integer amperage, String type) {
        super(TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD);

        setId(id);
        setRev(rev);
        setRevtype(revtype);
        setAmperage(amperage);
        setType(type);
        resetTouchedOnNotNull();
    }
}
