/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import pl.dabrowski.electrotools.jooq.tables.TProjects;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TProjectsRecord extends UpdatableRecordImpl<TProjectsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_projects.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_projects.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.t_projects.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_projects.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_projects.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_projects.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.t_projects.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_projects.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_projects.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_projects.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.t_projects.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_projects.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.t_projects.owner</code>.
     */
    public void setOwner(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_projects.owner</code>.
     */
    public String getOwner() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.t_projects.version</code>.
     */
    public void setVersion(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_projects.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TProjectsRecord
     */
    public TProjectsRecord() {
        super(TProjects.T_PROJECTS);
    }

    /**
     * Create a detached, initialised TProjectsRecord
     */
    public TProjectsRecord(UUID id, String createdBy, LocalDateTime createdDate, String modifiedBy, LocalDateTime modifiedDate, String name, String owner, Integer version) {
        super(TProjects.T_PROJECTS);

        setId(id);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setName(name);
        setOwner(owner);
        setVersion(version);
        resetTouchedOnNotNull();
    }
}
