/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import pl.dabrowski.electrotools.jooq.tables.TProjectsAud;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TProjectsAudRecord extends UpdatableRecordImpl<TProjectsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_projects_aud.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.t_projects_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.t_projects_aud.revtype</code>.
     */
    public void setRevtype(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.revtype</code>.
     */
    public Short getRevtype() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.t_projects_aud.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_projects_aud.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.t_projects_aud.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.t_projects_aud.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.t_projects_aud.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_projects_aud.owner</code>.
     */
    public void setOwner(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_projects_aud.owner</code>.
     */
    public String getOwner() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TProjectsAudRecord
     */
    public TProjectsAudRecord() {
        super(TProjectsAud.T_PROJECTS_AUD);
    }

    /**
     * Create a detached, initialised TProjectsAudRecord
     */
    public TProjectsAudRecord(UUID id, Integer rev, Short revtype, String createdBy, LocalDateTime createdDate, String modifiedBy, LocalDateTime modifiedDate, String name, String owner) {
        super(TProjectsAud.T_PROJECTS_AUD);

        setId(id);
        setRev(rev);
        setRevtype(revtype);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setName(name);
        setOwner(owner);
        resetTouchedOnNotNull();
    }
}
