/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import pl.dabrowski.electrotools.jooq.tables.TRcdElements;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TRcdElementsRecord extends UpdatableRecordImpl<TRcdElementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_rcd_elements.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.t_rcd_elements.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_rcd_elements.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.t_rcd_elements.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_rcd_elements.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.t_rcd_elements.version</code>.
     */
    public void setVersion(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.t_rcd_elements.label</code>.
     */
    public void setLabel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.label</code>.
     */
    public String getLabel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.t_rcd_elements.parent_id</code>.
     */
    public void setParentId(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.t_rcd_elements.diameter</code>.
     */
    public void setDiameter(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.diameter</code>.
     */
    public String getDiameter() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.t_rcd_elements.length</code>.
     */
    public void setLength(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.length</code>.
     */
    public Double getLength() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.t_rcd_elements.phase</code>.
     */
    public void setPhase(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.phase</code>.
     */
    public String getPhase() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.t_rcd_elements.placement</code>.
     */
    public void setPlacement(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.placement</code>.
     */
    public String getPlacement() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.t_rcd_elements.wire_type</code>.
     */
    public void setWireType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.wire_type</code>.
     */
    public String getWireType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.t_rcd_elements.x</code>.
     */
    public void setX(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.x</code>.
     */
    public Double getX() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.t_rcd_elements.y</code>.
     */
    public void setY(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.y</code>.
     */
    public Double getY() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.t_rcd_elements.diff_current</code>.
     */
    public void setDiffCurrent(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.diff_current</code>.
     */
    public Integer getDiffCurrent() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.t_rcd_elements.nominal_current</code>.
     */
    public void setNominalCurrent(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.nominal_current</code>.
     */
    public Integer getNominalCurrent() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.t_rcd_elements.pole_number</code>.
     */
    public void setPoleNumber(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.pole_number</code>.
     */
    public Integer getPoleNumber() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.t_rcd_elements.project_id</code>.
     */
    public void setProjectId(UUID value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements.project_id</code>.
     */
    public UUID getProjectId() {
        return (UUID) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcdElementsRecord
     */
    public TRcdElementsRecord() {
        super(TRcdElements.T_RCD_ELEMENTS);
    }

    /**
     * Create a detached, initialised TRcdElementsRecord
     */
    public TRcdElementsRecord(UUID id, String createdBy, LocalDateTime createdDate, String modifiedBy, LocalDateTime modifiedDate, Integer version, String label, UUID parentId, String diameter, Double length, String phase, String placement, String wireType, Double x, Double y, Integer diffCurrent, Integer nominalCurrent, Integer poleNumber, UUID projectId) {
        super(TRcdElements.T_RCD_ELEMENTS);

        setId(id);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
        setVersion(version);
        setLabel(label);
        setParentId(parentId);
        setDiameter(diameter);
        setLength(length);
        setPhase(phase);
        setPlacement(placement);
        setWireType(wireType);
        setX(x);
        setY(y);
        setDiffCurrent(diffCurrent);
        setNominalCurrent(nominalCurrent);
        setPoleNumber(poleNumber);
        setProjectId(projectId);
        resetTouchedOnNotNull();
    }
}
