/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import pl.dabrowski.electrotools.jooq.tables.TRcdElementsAud;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class TRcdElementsAudRecord extends UpdatableRecordImpl<TRcdElementsAudRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.t_rcd_elements_aud.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements_aud.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.t_rcd_elements_aud.rev</code>.
     */
    public void setRev(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements_aud.rev</code>.
     */
    public Integer getRev() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.t_rcd_elements_aud.revtype</code>.
     */
    public void setRevtype(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements_aud.revtype</code>.
     */
    public Short getRevtype() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.t_rcd_elements_aud.diff_current</code>.
     */
    public void setDiffCurrent(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements_aud.diff_current</code>.
     */
    public Integer getDiffCurrent() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.t_rcd_elements_aud.nominal_current</code>.
     */
    public void setNominalCurrent(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements_aud.nominal_current</code>.
     */
    public Integer getNominalCurrent() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.t_rcd_elements_aud.pole_number</code>.
     */
    public void setPoleNumber(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_rcd_elements_aud.pole_number</code>.
     */
    public Integer getPoleNumber() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRcdElementsAudRecord
     */
    public TRcdElementsAudRecord() {
        super(TRcdElementsAud.T_RCD_ELEMENTS_AUD);
    }

    /**
     * Create a detached, initialised TRcdElementsAudRecord
     */
    public TRcdElementsAudRecord(UUID id, Integer rev, Short revtype, Integer diffCurrent, Integer nominalCurrent, Integer poleNumber) {
        super(TRcdElementsAud.T_RCD_ELEMENTS_AUD);

        setId(id);
        setRev(rev);
        setRevtype(revtype);
        setDiffCurrent(diffCurrent);
        setNominalCurrent(nominalCurrent);
        setPoleNumber(poleNumber);
        resetTouchedOnNotNull();
    }
}
