/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;
import pl.dabrowski.electrotools.jooq.tables.*;
import pl.dabrowski.electrotools.jooq.tables.records.*;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RevinfoRecord> REVINFO_PKEY = Internal.createUniqueKey(Revinfo.REVINFO, DSL.name("revinfo_pkey"), new TableField[]{Revinfo.REVINFO.REV}, true);
    public static final UniqueKey<TBasicElementsRecord> T_BASIC_ELEMENTS_PKEY = Internal.createUniqueKey(TBasicElements.T_BASIC_ELEMENTS, DSL.name("t_basic_elements_pkey"), new TableField[]{TBasicElements.T_BASIC_ELEMENTS.ID}, true);
    public static final UniqueKey<TLoadElementsRecord> T_LOAD_ELEMENTS_PKEY = Internal.createUniqueKey(TLoadElements.T_LOAD_ELEMENTS, DSL.name("t_load_elements_pkey"), new TableField[]{TLoadElements.T_LOAD_ELEMENTS.ID}, true);
    public static final UniqueKey<TLoadElementsAudRecord> T_LOAD_ELEMENTS_AUD_PKEY = Internal.createUniqueKey(TLoadElementsAud.T_LOAD_ELEMENTS_AUD, DSL.name("t_load_elements_aud_pkey"), new TableField[]{TLoadElementsAud.T_LOAD_ELEMENTS_AUD.ID, TLoadElementsAud.T_LOAD_ELEMENTS_AUD.REV}, true);
    public static final UniqueKey<TOvercurrentProtectionElementsRecord> T_OVERCURRENT_PROTECTION_ELEMENTS_PKEY = Internal.createUniqueKey(TOvercurrentProtectionElements.T_OVERCURRENT_PROTECTION_ELEMENTS, DSL.name("t_overcurrent_protection_elements_pkey"), new TableField[]{TOvercurrentProtectionElements.T_OVERCURRENT_PROTECTION_ELEMENTS.ID}, true);
    public static final UniqueKey<TOvercurrentProtectionElementsAudRecord> T_OVERCURRENT_PROTECTION_ELEMENTS_AUD_PKEY = Internal.createUniqueKey(TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD, DSL.name("t_overcurrent_protection_elements_aud_pkey"), new TableField[]{TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD.ID, TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD.REV}, true);
    public static final UniqueKey<TProjectsRecord> T_PROJECTS_PKEY = Internal.createUniqueKey(TProjects.T_PROJECTS, DSL.name("t_projects_pkey"), new TableField[]{TProjects.T_PROJECTS.ID}, true);
    public static final UniqueKey<TProjectsAudRecord> T_PROJECTS_AUD_PKEY = Internal.createUniqueKey(TProjectsAud.T_PROJECTS_AUD, DSL.name("t_projects_aud_pkey"), new TableField[]{TProjectsAud.T_PROJECTS_AUD.ID, TProjectsAud.T_PROJECTS_AUD.REV}, true);
    public static final UniqueKey<TRcdElementsRecord> T_RCD_ELEMENTS_PKEY = Internal.createUniqueKey(TRcdElements.T_RCD_ELEMENTS, DSL.name("t_rcd_elements_pkey"), new TableField[]{TRcdElements.T_RCD_ELEMENTS.ID}, true);
    public static final UniqueKey<TRcdElementsAudRecord> T_RCD_ELEMENTS_AUD_PKEY = Internal.createUniqueKey(TRcdElementsAud.T_RCD_ELEMENTS_AUD, DSL.name("t_rcd_elements_aud_pkey"), new TableField[]{TRcdElementsAud.T_RCD_ELEMENTS_AUD.ID, TRcdElementsAud.T_RCD_ELEMENTS_AUD.REV}, true);
    public static final UniqueKey<TTerminalElementsRecord> T_TERMINAL_ELEMENTS_PKEY = Internal.createUniqueKey(TTerminalElements.T_TERMINAL_ELEMENTS, DSL.name("t_terminal_elements_pkey"), new TableField[]{TTerminalElements.T_TERMINAL_ELEMENTS.ID}, true);
    public static final UniqueKey<TTerminalElementsAudRecord> T_TERMINAL_ELEMENTS_AUD_PKEY = Internal.createUniqueKey(TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD, DSL.name("t_terminal_elements_aud_pkey"), new TableField[]{TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD.ID, TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD.REV}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TBasicElementsRecord, TProjectsRecord> T_BASIC_ELEMENTS__FK39DHW07WI5ST8PSYYUTES9193 = Internal.createForeignKey(TBasicElements.T_BASIC_ELEMENTS, DSL.name("fk39dhw07wi5st8psyyutes9193"), new TableField[]{TBasicElements.T_BASIC_ELEMENTS.PROJECT_ID}, Keys.T_PROJECTS_PKEY, new TableField[]{TProjects.T_PROJECTS.ID}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TLoadElementsRecord, TProjectsRecord> T_LOAD_ELEMENTS__FKAOPRM7AO3HVQ1QIIAD64VX71O = Internal.createForeignKey(TLoadElements.T_LOAD_ELEMENTS, DSL.name("fkaoprm7ao3hvq1qiiad64vx71o"), new TableField[]{TLoadElements.T_LOAD_ELEMENTS.PROJECT_ID}, Keys.T_PROJECTS_PKEY, new TableField[]{TProjects.T_PROJECTS.ID}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TLoadElementsAudRecord, RevinfoRecord> T_LOAD_ELEMENTS_AUD__FK6R8OHSI9BYDL4DU55OIW31GNT = Internal.createForeignKey(TLoadElementsAud.T_LOAD_ELEMENTS_AUD, DSL.name("fk6r8ohsi9bydl4du55oiw31gnt"), new TableField[]{TLoadElementsAud.T_LOAD_ELEMENTS_AUD.REV}, Keys.REVINFO_PKEY, new TableField[]{Revinfo.REVINFO.REV}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TOvercurrentProtectionElementsRecord, TProjectsRecord> T_OVERCURRENT_PROTECTION_ELEMENTS__FK6V1F3VVYO6I0LIU7VWPDE4SIQ = Internal.createForeignKey(TOvercurrentProtectionElements.T_OVERCURRENT_PROTECTION_ELEMENTS, DSL.name("fk6v1f3vvyo6i0liu7vwpde4siq"), new TableField[]{TOvercurrentProtectionElements.T_OVERCURRENT_PROTECTION_ELEMENTS.PROJECT_ID}, Keys.T_PROJECTS_PKEY, new TableField[]{TProjects.T_PROJECTS.ID}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TOvercurrentProtectionElementsAudRecord, RevinfoRecord> T_OVERCURRENT_PROTECTION_ELEMENTS_AUD__FKEBCFRE95GAUFT1EBO1RQUHE5T = Internal.createForeignKey(TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD, DSL.name("fkebcfre95gauft1ebo1rquhe5t"), new TableField[]{TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD.REV}, Keys.REVINFO_PKEY, new TableField[]{Revinfo.REVINFO.REV}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TProjectsAudRecord, RevinfoRecord> T_PROJECTS_AUD__FKCSISWK63MJ80MHBXGM7SYYIMW = Internal.createForeignKey(TProjectsAud.T_PROJECTS_AUD, DSL.name("fkcsiswk63mj80mhbxgm7syyimw"), new TableField[]{TProjectsAud.T_PROJECTS_AUD.REV}, Keys.REVINFO_PKEY, new TableField[]{Revinfo.REVINFO.REV}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TRcdElementsRecord, TProjectsRecord> T_RCD_ELEMENTS__FK74KAHOI0V42OTL9B42G55TH8G = Internal.createForeignKey(TRcdElements.T_RCD_ELEMENTS, DSL.name("fk74kahoi0v42otl9b42g55th8g"), new TableField[]{TRcdElements.T_RCD_ELEMENTS.PROJECT_ID}, Keys.T_PROJECTS_PKEY, new TableField[]{TProjects.T_PROJECTS.ID}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TRcdElementsAudRecord, RevinfoRecord> T_RCD_ELEMENTS_AUD__FKH6KI2JI6DG3BTUM8SHEMS7ES = Internal.createForeignKey(TRcdElementsAud.T_RCD_ELEMENTS_AUD, DSL.name("fkh6ki2ji6dg3btum8shems7es"), new TableField[]{TRcdElementsAud.T_RCD_ELEMENTS_AUD.REV}, Keys.REVINFO_PKEY, new TableField[]{Revinfo.REVINFO.REV}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TTerminalElementsRecord, TProjectsRecord> T_TERMINAL_ELEMENTS__FK2V3SAU5EQ0U5C735G5INPCVVU = Internal.createForeignKey(TTerminalElements.T_TERMINAL_ELEMENTS, DSL.name("fk2v3sau5eq0u5c735g5inpcvvu"), new TableField[]{TTerminalElements.T_TERMINAL_ELEMENTS.PROJECT_ID}, Keys.T_PROJECTS_PKEY, new TableField[]{TProjects.T_PROJECTS.ID}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TTerminalElementsAudRecord, RevinfoRecord> T_TERMINAL_ELEMENTS_AUD__FKIB9TINNVJAKFN4WRC7N877FTJ = Internal.createForeignKey(TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD, DSL.name("fkib9tinnvjakfn4wrc7n877ftj"), new TableField[]{TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD.REV}, Keys.REVINFO_PKEY, new TableField[]{Revinfo.REVINFO.REV}, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
