/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq;


import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import pl.dabrowski.electrotools.jooq.tables.*;

import java.util.Arrays;
import java.util.List;


/**
 * standard public schema
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.revinfo</code>.
     */
    public final Revinfo REVINFO = Revinfo.REVINFO;

    /**
     * The table <code>public.t_basic_elements</code>.
     */
    public final TBasicElements T_BASIC_ELEMENTS = TBasicElements.T_BASIC_ELEMENTS;

    /**
     * The table <code>public.t_load_elements</code>.
     */
    public final TLoadElements T_LOAD_ELEMENTS = TLoadElements.T_LOAD_ELEMENTS;

    /**
     * The table <code>public.t_load_elements_aud</code>.
     */
    public final TLoadElementsAud T_LOAD_ELEMENTS_AUD = TLoadElementsAud.T_LOAD_ELEMENTS_AUD;

    /**
     * The table <code>public.t_overcurrent_protection_elements</code>.
     */
    public final TOvercurrentProtectionElements T_OVERCURRENT_PROTECTION_ELEMENTS = TOvercurrentProtectionElements.T_OVERCURRENT_PROTECTION_ELEMENTS;

    /**
     * The table <code>public.t_overcurrent_protection_elements_aud</code>.
     */
    public final TOvercurrentProtectionElementsAud T_OVERCURRENT_PROTECTION_ELEMENTS_AUD = TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD;

    /**
     * The table <code>public.t_projects</code>.
     */
    public final TProjects T_PROJECTS = TProjects.T_PROJECTS;

    /**
     * The table <code>public.t_projects_aud</code>.
     */
    public final TProjectsAud T_PROJECTS_AUD = TProjectsAud.T_PROJECTS_AUD;

    /**
     * The table <code>public.t_rcd_elements</code>.
     */
    public final TRcdElements T_RCD_ELEMENTS = TRcdElements.T_RCD_ELEMENTS;

    /**
     * The table <code>public.t_rcd_elements_aud</code>.
     */
    public final TRcdElementsAud T_RCD_ELEMENTS_AUD = TRcdElementsAud.T_RCD_ELEMENTS_AUD;

    /**
     * The table <code>public.t_terminal_elements</code>.
     */
    public final TTerminalElements T_TERMINAL_ELEMENTS = TTerminalElements.T_TERMINAL_ELEMENTS;

    /**
     * The table <code>public.t_terminal_elements_aud</code>.
     */
    public final TTerminalElementsAud T_TERMINAL_ELEMENTS_AUD = TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
                Sequences.HIBERNATE_SEQUENCE,
                Sequences.REVINFO_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                Revinfo.REVINFO,
                TBasicElements.T_BASIC_ELEMENTS,
                TLoadElements.T_LOAD_ELEMENTS,
                TLoadElementsAud.T_LOAD_ELEMENTS_AUD,
                TOvercurrentProtectionElements.T_OVERCURRENT_PROTECTION_ELEMENTS,
                TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD,
                TProjects.T_PROJECTS,
                TProjectsAud.T_PROJECTS_AUD,
                TRcdElements.T_RCD_ELEMENTS,
                TRcdElementsAud.T_RCD_ELEMENTS_AUD,
                TTerminalElements.T_TERMINAL_ELEMENTS,
                TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD
        );
    }
}
