/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq;


import org.jooq.Sequence;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Sequences {

    /**
     * The sequence <code>public.hibernate_sequence</code>
     */
    public static final Sequence<Long> HIBERNATE_SEQUENCE = Internal.createSequence("hibernate_sequence", Public.PUBLIC, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.revinfo_seq</code>
     */
    public static final Sequence<Long> REVINFO_SEQ = Internal.createSequence("revinfo_seq", Public.PUBLIC, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, 50, null, null, false, null);
}
