/*
 * This file is generated by jOOQ.
 */
package pl.dabrowski.electrotools.jooq;


import pl.dabrowski.electrotools.jooq.tables.*;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>public.revinfo</code>.
     */
    public static final Revinfo REVINFO = Revinfo.REVINFO;

    /**
     * The table <code>public.t_basic_elements</code>.
     */
    public static final TBasicElements T_BASIC_ELEMENTS = TBasicElements.T_BASIC_ELEMENTS;

    /**
     * The table <code>public.t_load_elements</code>.
     */
    public static final TLoadElements T_LOAD_ELEMENTS = TLoadElements.T_LOAD_ELEMENTS;

    /**
     * The table <code>public.t_load_elements_aud</code>.
     */
    public static final TLoadElementsAud T_LOAD_ELEMENTS_AUD = TLoadElementsAud.T_LOAD_ELEMENTS_AUD;

    /**
     * The table <code>public.t_overcurrent_protection_elements</code>.
     */
    public static final TOvercurrentProtectionElements T_OVERCURRENT_PROTECTION_ELEMENTS = TOvercurrentProtectionElements.T_OVERCURRENT_PROTECTION_ELEMENTS;

    /**
     * The table <code>public.t_overcurrent_protection_elements_aud</code>.
     */
    public static final TOvercurrentProtectionElementsAud T_OVERCURRENT_PROTECTION_ELEMENTS_AUD = TOvercurrentProtectionElementsAud.T_OVERCURRENT_PROTECTION_ELEMENTS_AUD;

    /**
     * The table <code>public.t_projects</code>.
     */
    public static final TProjects T_PROJECTS = TProjects.T_PROJECTS;

    /**
     * The table <code>public.t_projects_aud</code>.
     */
    public static final TProjectsAud T_PROJECTS_AUD = TProjectsAud.T_PROJECTS_AUD;

    /**
     * The table <code>public.t_rcd_elements</code>.
     */
    public static final TRcdElements T_RCD_ELEMENTS = TRcdElements.T_RCD_ELEMENTS;

    /**
     * The table <code>public.t_rcd_elements_aud</code>.
     */
    public static final TRcdElementsAud T_RCD_ELEMENTS_AUD = TRcdElementsAud.T_RCD_ELEMENTS_AUD;

    /**
     * The table <code>public.t_terminal_elements</code>.
     */
    public static final TTerminalElements T_TERMINAL_ELEMENTS = TTerminalElements.T_TERMINAL_ELEMENTS;

    /**
     * The table <code>public.t_terminal_elements_aud</code>.
     */
    public static final TTerminalElementsAud T_TERMINAL_ELEMENTS_AUD = TTerminalElementsAud.T_TERMINAL_ELEMENTS_AUD;
}
